# Ubuntu 14.04 Trusty support
#sudo: required
#dist: trusty
# Enable C++ support
language: cpp
# Compiler selection
compiler:
  - gcc
#before_install:
#  - sudo apt-get -qq update
# Build steps
script:
  - mkdir build
  - cd build
  - cmake .. && make
